version: '3.3'

services:
  app:
    depends_on:
      - db
    image: "wordpress:${WORDPRESS_VERSION:-6.6}"
    ports:
      - "${APP_PORT:-8000}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - .:/var/www/html/wp-content/plugins/AloPeyk-WooCommerce-Plugin
  db:
    image: "mysql:${MYSQL_VERSION:-5.7}"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
volumes:
  db_data: { }
